server:
  port: 9900
#  servlet:
#    context-path: /mutlidatasource
spring:
  datasource:
    default:
      username: root
      password: tang
  #    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      url: jdbc:mysql://localhost:3306/test?useUnicode=true
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      #初始大小
      initialSize: 5
      #最小
      minIdle: 5
      #最大
      maxActive: 20
      #获取连接等待超时时间
      maxWait: 60000
    test1:
      username: root
      password: tang
      #    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      url: jdbc:mysql://localhost:3306/test?useUnicode=true
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      #初始大小
      initialSize: 5
      #最小
      minIdle: 5
      #最大
      maxActive: 20
      #获取连接等待超时时间
      maxWait: 60000


# mybatis 配置
mybatis:
  mapper-locations: classpath*:com/example/demo/hello/dao/*DAO.xml
  type-aliases-package: com.example.demo.hello.dao