server:
  port: 9900
#  servlet:
#    context-path: /mutlidatasource
spring:
  datasource:
    username: root
    password: tang
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis 配置
mybatis:
  mapper-locations: classpath*:com/example/demo/hello/dao/*DAO.xml
  type-aliases-package: com.example.demo.hello.dao